[unstable]
build-std = ["core", "alloc", "std"]

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=-s",
    "-C", "link-arg=--gc-sections",
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--allow-undefined",
]
