
-- FMIS03.MIE
level = {
    name = ">RULES",
    start_position = { x = 280, y = 280 },
    sound_start = "ZPARA",
    messages = [
        
    ],
    objects = [
        {'type': 'collectible', 'position': {'x': 32, 'y': 20}, 'value': 5, 'name': 'ZNNC', 'layer': 'C', 'other_data': ['67', '3']},
        {'type': 'collectible', 'position': {'x': 70, 'y': 43}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 70, 'y': 41}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 72, 'y': 41}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 72, 'y': 43}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 72, 'y': 45}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 74, 'y': 45}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 74, 'y': 43}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 74, 'y': 41}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 76, 'y': 41}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 76, 'y': 43}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 76, 'y': 45}, 'value': 50, 'name': 'ZNNB', 'layer': 'B', 'other_data': ['66', '3']},
        {'type': 'collectible', 'position': {'x': 34, 'y': 20}, 'value': 5, 'name': 'ZNNC', 'layer': 'C', 'other_data': ['67', '3']},
        {'type': 'collectible', 'position': {'x': 36, 'y': 20}, 'value': 5, 'name': 'ZNNC', 'layer': 'C', 'other_data': ['67', '3']},
        {'type': 'collectible', 'position': {'x': 36, 'y': 18}, 'value': 5, 'name': 'ZNNC', 'layer': 'C', 'other_data': ['67', '3']},
        {'type': 'collectible', 'position': {'x': 34, 'y': 18}, 'value': 5, 'name': 'ZNNC', 'layer': 'C', 'other_data': ['67', '3']},
        {'type': 'collectible', 'position': {'x': 32, 'y': 18}, 'value': 5, 'name': 'ZNNC', 'layer': 'C', 'other_data': ['67', '3']},
        {'type': 'collectible', 'position': {'x': 32, 'y': 16}, 'value': 5, 'name': 'ZNNC', 'layer': 'C', 'other_data': ['67', '3']},
        {'type': 'collectible', 'position': {'x': 34, 'y': 16}, 'value': 5, 'name': 'ZNNC', 'layer': 'C', 'other_data': ['67', '3']},
        {'type': 'collectible', 'position': {'x': 36, 'y': 16}, 'value': 5, 'name': 'ZNNC', 'layer': 'C', 'other_data': ['67', '3']},
        {'type': 'collectible', 'position': {'x': 28, 'y': 45}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 30, 'y': 45}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 32, 'y': 45}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 34, 'y': 45}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 36, 'y': 45}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 38, 'y': 45}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 40, 'y': 45}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'special', 'position': {'x': 0, 'y': 33}, 'value': 45, 'name': 'YNNA', 'layer': 'A', 'other_data': ['6', '8'], 'animated': False, 'dangerous': False},
        {'type': 'special', 'position': {'x': 76, 'y': 33}, 'value': 45, 'name': 'YNNA', 'layer': 'A', 'other_data': ['6', '68'], 'animated': False, 'dangerous': False},
        {'type': 'special', 'position': {'x': 39, 'y': 20}, 'value': 10, 'name': 'YNNC', 'layer': 'C', 'other_data': ['6', '30'], 'animated': False, 'dangerous': False},
        {'type': 'special', 'position': {'x': 26, 'y': 10}, 'value': 1, 'name': 'YASA', 'layer': 'A', 'other_data': ['5', '2'], 'animated': False, 'dangerous': False}
    ],
    map = [[
        .......................................
        .......................................
        .......................................
        .......................................
        .......................................
        .......................................
        ...............'...&...................
        ...............'...&...................
        ...............'...&...................
        ...............'...&...................
        ...............'...&...................
        .......%!!!!!!!6!!!7!!!!!!!!!!$........
        ......%"......................#$.......
        .....%"........................#$......
        ....%"..........................#$.....
        ...%"............................#$....
        ..%"..............................#$...
        ...............(...(...................
        (((((...((...............((.(((...(((((
        ....@....((......(......((........?....
        ....@.....((...........((.........?....
        ....@......((..(...(..((..........?....
        ....@..........(((((..............?....
        ....@........(.......(.......R....?....
        (((((((((((((((((((((((((((((((((((((((
        .......................................
        .......................................
    ]]
}
