
-- FMIS08.MIE
level = {
    name = ">PACMAN",
    start_position = { x = 16, y = 360 },
    sound_start = "ZROCK",
    messages = {
        
    },
    objects = {
        {type = 'collectible', position = {x = 76, y = 30}, value = 150, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 6, y = 43}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 12, y = 42}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 26, y = 43}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 25, y = 2}, value = 100, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 74, y = 39}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 64, y = 34}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 75, y = 47}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 46, y = 23}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 34, y = 11}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 36, y = 11}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 38, y = 11}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 40, y = 11}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 26, y = 23}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 21, y = 9}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 12, y = 28}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 12, y = 30}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 12, y = 32}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 12, y = 34}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 12, y = 36}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 12, y = 38}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 12, y = 40}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 30, y = 25}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 30, y = 27}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 30, y = 29}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 30, y = 31}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 43, y = 30}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 16, y = 45}, value = 10, name = 'ZANA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 18, y = 45}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 20, y = 45}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 22, y = 45}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 24, y = 45}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 26, y = 45}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 28, y = 45}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 28, y = 43}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 24, y = 43}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 43, y = 36}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 36, y = 23}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 59, y = 45}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 52, y = 26}, value = 10, name = 'ZANA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 67, y = 34}, value = 10, name = 'ZANA', layer = 'A', other_data = {1, 3}},
        {type = 'special', position = {x = 34, y = 11}, value = 40, name = 'YASA', layer = 'A', other_data = {2, 34}},
        {type = 'special', position = {x = 20, y = 10}, value = 1, name = 'YASA', layer = 'A', other_data = {5, 3}},
        {type = 'special', position = {x = 45, y = 18}, value = 1, name = 'YASA', layer = 'A', other_data = {5, 3}}
    },
    map = {
        ".......................................",
        ".......................................",
        "...............dd......................",
        "...................Y...................",
        "..................dd...................",
        "...........3////.......................",
        "...........5....C....C.................",
        "...........5....@C@C@C...//..//........",
        ".........3/0...........................",
        ".........5.............................",
        ".......3/0.............................",
        ".....3/0...............................",
        "V...30.................................",
        "2..30.......3/...//2...//2.............",
        "12.........30......12....1//2......Y...",
        ".12.......30........1.......12.....12..",
        "..12.....30..................12.....12.",
        "...1/.../0....................12.....ED",
        "...............................1///2..5",
        ".....................32............E/.5",
        "....................3012..............5",
        "...................30..1/2....3///.3//0",
        "..................30.....1/2.......0...",
        "...............3//0........1/2.........",
        "///////////////0.............1/2.......",
        "CCCC>@@@@@@CCCC................1///////",
        "......................................."
    }
}
