
-- FMIS07.MIE
level = {
    name = ">ONEHALF",
    start_position = { x = 424, y = 72 },
    sound_start = "ZROCK",
    messages = [
        {'lang': 'EN', 'text': 'Press ENTER to activate teleport.'},
        {'lang': 'SK', 'text': 'Stlaç ENTER na aktiváciu teleportu.'}
    ],
    objects = [
        {'type': 'collectible', 'position': {'x': 12, 'y': 15}, 'value': 50, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 5, 'y': 45}, 'value': 5, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 7, 'y': 45}, 'value': 5, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 9, 'y': 45}, 'value': 5, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 11, 'y': 45}, 'value': 5, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 13, 'y': 45}, 'value': 5, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 10, 'y': 9}, 'value': 5, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 18, 'y': 9}, 'value': 5, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 66, 'y': 43}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 36, 'y': 43}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 42, 'y': 43}, 'value': 10, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 60, 'y': 43}, 'value': 10, 'name': 'ZANA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 14, 'y': 15}, 'value': 50, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 37, 'y': 23}, 'value': 15, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 35, 'y': 25}, 'value': 15, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 33, 'y': 27}, 'value': 15, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 72, 'y': 19}, 'value': 15, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 74, 'y': 19}, 'value': 15, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'collectible', 'position': {'x': 70, 'y': 19}, 'value': 15, 'name': 'ZNNA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'trigger', 'position': {'x': 51, 'y': 37}, 'value': 3, 'name': 'XANA', 'layer': 'A', 'other_data': ['1', '3']},
        {'type': 'trigger', 'position': {'x': 1, 'y': 46}, 'value': 37, 'name': 'XNNA', 'layer': 'A', 'other_data': ['1', '51']},
        {'type': 'trigger', 'position': {'x': 76, 'y': 20}, 'value': 45, 'name': 'XNNA', 'layer': 'A', 'other_data': ['1', '0']},
        {'type': 'trigger', 'position': {'x': 51, 'y': 45}, 'value': 5, 'name': 'XANA', 'layer': 'A', 'other_data': ['1', '8']},
        {'type': 'special', 'position': {'x': 62, 'y': 20}, 'value': 45, 'name': 'YANA', 'layer': 'A', 'other_data': ['1', '51'], 'animated': False, 'dangerous': False},
        {'type': 'special', 'position': {'x': 53, 'y': 24}, 'value': 1, 'name': 'YASA', 'layer': 'A', 'other_data': ['4', '3'], 'animated': False, 'dangerous': False},
        {'type': 'specrial', 'position': {'x': 49, 'y': 24}, 'value': 0, 'name': 'YASA', 'layer': 'A', 'other_data': ['4', '3'], 'animated': False, 'dangerous': False},
        {'type': 'special', 'position': {'x': 74, 'y': 19}, 'value': 0, 'name': 'YASA', 'layer': 'A', 'other_data': ['4', '3'], 'animated': False, 'dangerous': False}
    ],
    map = [[
        .......................................
        .......................................
        .......................................
        .......................................
        ...../.../..............(...(..........
        .......................................
        ..........................(............
        ..........................(............
        ...../.../..............(...(..........
        ......./................(((((..........
        .......................................
        ....................%!!!!!!!!!!!!!!!!!!
        ...................%"..................
        ..................%"...................
        .................%"....................
        ................%".....................
        ...............%"............3044......
        ..............%".(..................(((
        .............%"..(..................(..
        ............%"...(.................((..
        ...........%"....(......((((.......(...
        ..........%".....(.....((..((.....((...
        .........%"......(....((....((....(....
        ........%".......((((((L....L((((((....
        !!!!!!!!"............&43212355'........
        .....................#!!!!!!!!"........
        .......................................
    ]]
}
