
-- FMIS11.MIE
level = {
    name = ">RAILWAY",
    start_position = { x = 344, y = 184 },
    sound_start = "ZSCHUB",
    messages = {
        
    },
    objects = {
        {type = 'collectible', position = {x = 4, y = 15}, value = 100, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 7, y = 15}, value = 100, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 10, y = 15}, value = 100, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 21, y = 37}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 33, y = 37}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 45, y = 37}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 57, y = 37}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 70, y = 37}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 28, y = 21}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 68, y = 47}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 64, y = 47}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 52, y = 47}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 44, y = 47}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 36, y = 47}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 28, y = 47}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 20, y = 47}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 12, y = 47}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 27, y = 37}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 39, y = 37}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 51, y = 37}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 63, y = 37}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 16, y = 25}, value = 50, name = 'ZAND', layer = 'D', other_data = {68, 3}},
        {type = 'collectible', position = {x = 14, y = 27}, value = 50, name = 'ZAND', layer = 'D', other_data = {68, 3}},
        {type = 'special', position = {x = 4, y = 29}, value = 65, name = 'YASA', layer = 'A', other_data = {2, 4}},
        {type = 'special', position = {x = 4, y = 47}, value = 67, name = 'YASA', layer = 'A', other_data = {2, 4}},
        {type = 'special', position = {x = 72, y = 37}, value = 72, name = 'YASA', layer = 'A', other_data = {2, 12}}
    },
    map = {
        ".......................................",
        ".......................................",
        ".......................................",
        ".......................................",
        ".......................................",
        ".......................................",
        ".......................................",
        ".......................................",
        ".a.....a...............................",
        ".HFKFFGMZZ........6...6................",
        ".........ZZ.........6..................",
        "...............V....6..................",
        ".......<=..AAA?>..6WX.6................",
        "......<=.J[]I.....66666................",
        ".....<<................................",
        ".Y...................YY.....`..........",
        "M666666666Z6666Z666Z66666666N6666R.....",
        "................................ZZR....",
        ".......................................",
        ".........V..V..V..V..V..V..V..V..V...BB",
        "......AAAABBBCBBCAA@??@AA?>>@@@@AABBCBV",
        "......B...............................V",
        ".....BB...............................V",
        "......................................V",
        "T.aWXa.WXa.WXa.WXa.WXa.WXa.WXaWX.a.T...",
        "bbbbcdddebbbbccccddebbbbcccbcbcdebbcccd",
        "......................................."
    }
}
