
-- FMIS09.MIE
level = {
    name = ">SABREWOLF",
    start_position = { x = 488, y = 152 },
    sound_start = "ZROCK",
    messages = {
        
    },
    objects = {
        {type = 'collectible', position = {x = 10, y = 42}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 48, y = 0}, value = 100, name = 'ZANA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 59, y = 25}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 52, y = 45}, value = 50, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 60, y = 45}, value = 50, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 68, y = 45}, value = 50, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 76, y = 45}, value = 50, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 58, y = 27}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 61, y = 25}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 60, y = 27}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 62, y = 27}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 6, y = 13}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 8, y = 27}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 16, y = 33}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 14, y = 41}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 30, y = 20}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 34, y = 20}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 38, y = 20}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 42, y = 20}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 46, y = 20}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 50, y = 20}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 32, y = 18}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 36, y = 18}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 40, y = 18}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 44, y = 18}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 48, y = 18}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 52, y = 18}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 34, y = 4}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 36, y = 4}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 50, y = 39}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 31, y = 30}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 48, y = 30}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 0, y = 11}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 0, y = 24}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 52, y = 41}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 60, y = 41}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 68, y = 41}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 76, y = 41}, value = 5, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 52, y = 43}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 60, y = 43}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 68, y = 43}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 76, y = 43}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 54, y = 0}, value = 500, name = 'ZANA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 10, y = 45}, value = 30, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 54, y = 4}, value = 100, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 48, y = 4}, value = 100, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 42, y = 4}, value = 100, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'special', position = {x = 56, y = 25}, value = 5, name = 'YNNA', layer = 'A', other_data = {6, 22}},
        {type = 'special', position = {x = 14, y = 1}, value = 0, name = 'YASA', layer = 'A', other_data = {5, 3}},
        {type = 'special', position = {x = 42, y = 0}, value = 4, name = 'YASB', layer = 'B', other_data = {3, 0}},
        {type = 'special', position = {x = 31, y = 0}, value = 4, name = 'YASB', layer = 'B', other_data = {3, 0}},
        {type = 'special', position = {x = 12, y = 17}, value = 54, name = 'YASA', layer = 'A', other_data = {2, 12}}
    },
    map = {
        ".......................................",
        ".......................................",
        ".......................................",
        ".........3//........./../../...........",
        "........30.............................",
        "........5..............................",
        "...3////0..............................",
        "12.....................................",
        ".12.........................6...6......",
        "..1//2.................................",
        ".....1//..3////././././././............",
        ".........30...................6........",
        "........30....................6........",
        "/2..3///0..............................",
        ".12.........................6...6......",
        "..12........................66666......",
        "...12.........3//////////..............",
        "....1//2......5........................",
        ".......E/....30..........V.............",
        ".............5.........................",
        ".......3///NN0.........................",
        ".......................;97.............",
        "....3/2..............;97f7.............",
        "....5.4............;9777f7.............",
        ".................;977f77776...6...6...6",
        "777777777f77777777777777777777777777777",
        "......................................."
    }
}
