
-- FMIS12.MIE
level = {
    name = ">FLOATER",
    start_position = { x = 232, y = 80 },
    sound_start = "ZSCHUB",
    messages = {
        
    },
    objects = {
        {type = 'collectible', position = {x = 10, y = 23}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 14, y = 23}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 18, y = 23}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 23, y = 23}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 42, y = 23}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 47, y = 23}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 52, y = 23}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 57, y = 23}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 63, y = 23}, value = 10, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 12, y = 27}, value = 5, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 16, y = 27}, value = 5, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 21, y = 27}, value = 5, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 44, y = 27}, value = 5, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 49, y = 27}, value = 5, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 55, y = 27}, value = 5, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 60, y = 27}, value = 5, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 14, y = 31}, value = 50, name = 'ZANB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 25, y = 31}, value = 50, name = 'ZANB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 39, y = 31}, value = 50, name = 'ZANB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 52, y = 31}, value = 50, name = 'ZANB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 64, y = 31}, value = 50, name = 'ZANB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 11, y = 35}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 18, y = 35}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 31, y = 35}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 46, y = 35}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 57, y = 35}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 13, y = 39}, value = 30, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 32, y = 31}, value = 30, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 57, y = 19}, value = 30, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 14, y = 19}, value = 30, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 60, y = 39}, value = 30, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 33, y = 39}, value = 35, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 23, y = 43}, value = 35, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 48, y = 43}, value = 35, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 28, y = 15}, value = 40, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 30, y = 15}, value = 40, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 32, y = 15}, value = 40, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 34, y = 15}, value = 40, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 36, y = 15}, value = 40, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 6, y = 43}, value = 150, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 6, y = 35}, value = 150, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 6, y = 27}, value = 150, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 6, y = 19}, value = 150, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 68, y = 23}, value = 200, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 68, y = 39}, value = 200, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'special', position = {x = 76, y = 19}, value = 76, name = 'YASB', layer = 'B', other_data = {2, 0}},
        {type = 'special', position = {x = 0, y = 23}, value = 76, name = 'YASB', layer = 'B', other_data = {2, 0}},
        {type = 'special', position = {x = 76, y = 27}, value = 76, name = 'YASB', layer = 'B', other_data = {2, 0}},
        {type = 'special', position = {x = 0, y = 31}, value = 76, name = 'YASB', layer = 'B', other_data = {2, 0}},
        {type = 'special', position = {x = 76, y = 35}, value = 76, name = 'YASB', layer = 'B', other_data = {2, 0}},
        {type = 'special', position = {x = 0, y = 39}, value = 76, name = 'YASB', layer = 'B', other_data = {2, 0}},
        {type = 'special', position = {x = 6, y = 43}, value = 47, name = 'YASB', layer = 'B', other_data = {3, 43}}
    },
    map = {
        ".......................................",
        ".......................................",
        ".......................................",
        "..............6...6....................",
        "................6......................",
        "................6.Y....................",
        "..............6...6....................",
        "..............66666....................",
        "aaaaaa....Y.............Y.........T....",
        "6666666666666666666666666666666666N....",
        "......................................U",
        "...M66666666666666666666666666666666666",
        "T......................................",
        "6666666666666666666666666666666666N....",
        ".....................................YU",
        "...M66666666666P6O666666666666666666666",
        "T......................................",
        "6666666666666666666666666666666666N....",
        "......................................U",
        "...M66666666666666666666666666666666666",
        "T......................................",
        "6666666666666666666666666666666666N....",
        ".....................................`U",
        "...M66666666666666666666666666666666666",
        "T.....................................V",
        "666666666666666666666666666666666666666",
        "......................................."
    }
}
