
-- FMIS04.MIE
level = {
    name = ">RAIDER",
    start_position = { x = 248, y = 8 },
    sound_start = "ZPARA",
    messages = {
        
    },
    objects = {
        {type = 'collectible', position = {x = 8, y = 15}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 6, y = 15}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 4, y = 15}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 2, y = 15}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 0, y = 15}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 1, y = 13}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 3, y = 13}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 5, y = 13}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 7, y = 13}, value = 10, name = 'ZNNA', layer = 'A', other_data = {1, 3}},
        {type = 'collectible', position = {x = 16, y = 43}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 20, y = 43}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 23, y = 43}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 26, y = 43}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 29, y = 43}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 32, y = 43}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 35, y = 43}, value = 15, name = 'ZNNB', layer = 'B', other_data = {66, 3}},
        {type = 'collectible', position = {x = 41, y = 43}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 43, y = 43}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 45, y = 43}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 47, y = 43}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 50, y = 43}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 52, y = 43}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 54, y = 43}, value = 5, name = 'ZNNC', layer = 'C', other_data = {67, 3}},
        {type = 'collectible', position = {x = 0, y = 43}, value = 50, name = 'ZAND', layer = 'D', other_data = {68, 3}},
        {type = 'collectible', position = {x = 76, y = 43}, value = 50, name = 'ZAND', layer = 'D', other_data = {68, 3}},
        {type = 'special', position = {x = 38, y = 4}, value = 1, name = 'YASD', layer = 'D', other_data = {5, 2}},
        {type = 'special', position = {x = 36, y = 43}, value = 36, name = 'YASC', layer = 'C', other_data = {2, 15}},
        {type = 'special', position = {x = 29, y = 29}, value = 19, name = 'YNNA', layer = 'A', other_data = {6, 68}},
        {type = 'special', position = {x = 41, y = 41}, value = 51, name = 'YASE', layer = 'E', other_data = {2, 41}},
        {type = 'special', position = {x = 46, y = 43}, value = 56, name = 'YASE', layer = 'E', other_data = {2, 46}}
    },
    map = {
        ".......................................",
        ".............6...6.....................",
        "...............6.......................",
        "...............6.......................",
        ".............6...6.....................",
        ".............66666.////2...............",
        ".......................4...............",
        "......................3E//2............",
        ".....HI...................1////2.......",
        "666666QI...............................",
        "6666666QI.......................S6NN66.",
        "........HI.....`...............S66.666.",
        ".........HFFKI.bc........Y..Y.S6666666.",
        "................cd......66666666666666.",
        ".................de.AA.......5.........",
        "...........U....T....AA......5.........",
        "...........[\\\\].....BB.....5.........",
        ".......................BB...3D.........",
        "...........................30..........",
        "..........................30...........",
        "..........................0............",
        ".......................................",
        "....3.T............Y...........U.2.....",
        "////0ZZZZ6ZZZZZ66M6ZZZZM6666ZZZZZ1/////",
        ".......................................",
        ".......................................",
        "......................................."
    }
}
